

import { Subject } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: "web-design",
    title: "Web Designing",
    description: "Master HTML, CSS, XML, JavaScript, and PHP for full-stack development.",
    icon: "Code",
    chapters: [
      {
        id: "1",
        title: "1. Principles of Web Designing and HTML",
        topics: [
          { id: "1.1", title: "1.1 Describe the anatomy of web page" },
          { id: "1.2", title: "1.2 Illustrate the format of web page" },
          { id: "1.3", title: "1.3 Identify various Web page elements" },
          { id: "1.4", title: "1.4 Explain the process of navigation through web pages" },
          { id: "1.5", title: "1.5 State the steps in building a web site" },
          { id: "1.6", title: "1.6 State the steps in launching a web site" },
          { id: "1.7", title: "1.7 State the steps in maintaining a web site" },
          { id: "1.8", title: "1.8 Describe the importance of HTML" },
          { id: "1.9", title: "1.9 Use the basic tags <html>, <head>, <title>, <body>" },
          { id: "1.10", title: "1.10 Use headings and text formatting tags (h1-h6, strong, cite, etc.)" },
          { id: "1.11", title: "1.11 Use presentation tags (b, i, u, sub, sup, font, marquee)" },
        ]
      },
      {
        id: "2",
        title: "2. HTML Tags and Style Sheets",
        topics: [
          { id: "2.1", title: "2.1 Use the hyperlink and imaging tags with attributes" },
          { id: "2.2", title: "2.2 Use the <object> tag with attributes" },
          { id: "2.3", title: "2.3 Use the listing tags along with attributes" },
          { id: "2.4", title: "2.4 Use colors to various HTML elements" },
          { id: "2.5", title: "2.5 Use table creation tags (table, tr, td, th, etc.)" },
          { id: "2.6", title: "2.6 Use form control tags (form, input, button, select, textarea)" },
          { id: "2.7", title: "2.7 Use frame tags (frame, frameset, iframe)" },
          { id: "2.8.1", title: "2.8.1 Create Inline styles" },
          { id: "2.8.2", title: "2.8.2 Create embedded style sheets" },
          { id: "2.8.3", title: "2.8.3 Link external style sheets to a HTML page" },
          { id: "2.8.4", title: "2.8.4 Place HTML elements at required position" },
          { id: "2.8.5", title: "2.8.5 Change background colours, images etc." },
          { id: "2.8.6", title: "2.8.6 Set properties: margin, padding, height, width" },
          { id: "2.9", title: "2.9 List the applications of HTML" },
        ]
      },
      {
        id: "3",
        title: "3. XML and Web Servers",
        topics: [
          { id: "3.1.1", title: "3.1.1 Describe the organization of data in the form of XML" },
          { id: "3.1.2", title: "3.1.2 State the significance of Namespace" },
          { id: "3.1.3", title: "3.1.3 Compare and Contrast DTD and Schema" },
          { id: "3.1.4", title: "3.1.4 Understand the parsing process of XML by DOM and SAX" },
          { id: "3.1.5", title: "3.1.5 List the applications of XML" },
          { id: "3.2.1", title: "3.2.1 Distinguish Client-side and Server-side scripting" },
          { id: "3.2.2", title: "3.2.2 Illustrate the architecture of Web server" },
          { id: "3.2.3", title: "3.2.3 Identify various HTTP request types" },
          { id: "3.2.4", title: "3.2.4 Understand installation of IIS, PWS and Apache" },
          { id: "3.2.5", title: "3.2.5 Compare/Contrast IIS, PWS and Apache" },
        ]
      },
      {
        id: "4",
        title: "4. Client Side Scripting (JavaScript)",
        topics: [
          { id: "4.1", title: "4.1 Describe the need for client side scripting" },
          { id: "4.2", title: "4.2 List various client side scripting languages" },
          { id: "4.3", title: "4.3 Use various operators" },
          { id: "4.4", title: "4.4 Use if, if/else and switch statements" },
          { id: "4.5", title: "4.5 Use while, do/while and for iterative statements" },
          { id: "4.6", title: "4.6 Write small programs using conditional/iterative statements" },
          { id: "4.7", title: "4.7 Understand the process of debugging JavaScript code" },
          { id: "4.8.1", title: "4.8.1 Define and call a function" },
          { id: "4.8.2", title: "4.8.2 Illustrate parameter passing" },
          { id: "4.8.3", title: "4.8.3 List global functions provided by JavaScript" },
          { id: "4.8.4", title: "4.8.4 Explain scope and lifetime of variables" },
          { id: "4.8.5", title: "4.8.5 Write small programs using recursion" },
          { id: "4.9.1", title: "4.9.1 Understand single and multi dimensional arrays" },
          { id: "4.9.2", title: "4.9.2 Declare an array" },
          { id: "4.9.3", title: "4.9.3 Manipulate an array" },
          { id: "4.9.4", title: "4.9.4 Write small programs using arrays" },
          { id: "4.10", title: "4.10 List various Objects provided by JavaScript" },
        ]
      },
      {
        id: "5",
        title: "5. Introduction to PHP",
        topics: [
          { id: "5.1", title: "5.1 Understand the installation of PHP" },
          { id: "5.2", title: "5.2 PHP basics and features" },
          { id: "5.3", title: "5.3 Embedding PHP in HTML" },
          { id: "5.4", title: "5.4 List and explain various Data types" },
          { id: "5.5", title: "5.5 Declare variables and constants" },
          { id: "5.6", title: "5.6 Use various Operators" },
          { id: "5.7", title: "5.7 Implement conditional statements" },
          { id: "5.8", title: "5.8 Implement various loop statements" },
          { id: "5.9", title: "5.9 Write programs using loops and conditional statements" },
          { id: "5.10", title: "5.10 Explain about Strings and String Methods" },
          { id: "5.11.1", title: "5.11.1 Understand single and multi dimensional arrays in PHP" },
          { id: "5.11.2", title: "5.11.2 Declare an array" },
          { id: "5.11.3", title: "5.11.3 Manipulate an array" },
          { id: "5.11.4", title: "5.11.4 Array Methods" },
          { id: "5.11.5", title: "5.11.5 Write programs using arrays and Array Methods" },
        ]
      },
      {
        id: "6",
        title: "6. Advanced Server Side Scripting (PHP)",
        topics: [
          { id: "6.1.1", title: "6.1.1 Define user defined function" },
          { id: "6.1.2", title: "6.1.2 State the importance of user defined function" },
          { id: "6.1.3", title: "6.1.3 Describe the process of passing arguments" },
          { id: "6.1.4", title: "6.1.4 Explain the scope and lifetime of variables" },
          { id: "6.1.5", title: "6.1.5 Write programs using functions" },
          { id: "6.1.6", title: "6.1.6 Using Recursive Functions" },
          { id: "6.2.1", title: "6.2.1 Define PHP Classes" },
          { id: "6.2.2", title: "6.2.2 Creating objects in PHP" },
          { id: "6.2.3", title: "6.2.3 Calling member functions" },
          { id: "6.2.4", title: "6.2.4 Inheritance" },
          { id: "6.2.5", title: "6.2.5 Function overriding" },
          { id: "6.2.6", title: "6.2.6 Creating a class constructor" },
          { id: "6.3.1", title: "6.3.1 Global and environmental variables" },
          { id: "6.3.2", title: "6.3.2 GET and POST methods" },
          { id: "6.3.3", title: "6.3.3 Script to access user input" },
          { id: "6.3.4", title: "6.3.4 Accessing input from various elements of a form" },
          { id: "6.3.5", title: "6.3.5 File uploading in PHP" },
          { id: "6.4.1", title: "6.4.1 Define Session and Cookie" },
          { id: "6.4.2", title: "6.4.2 Setting or creating a cookie in PHP" },
          { id: "6.4.3", title: "6.4.3 Retrieving and deleting cookie" },
          { id: "6.4.4", title: "6.4.4 Creating Session Cookie" },
          { id: "6.4.5", title: "6.4.5 Understand Session function in PHP" },
          { id: "6.4.6", title: "6.4.6 Use session variables" },
          { id: "6.5.1", title: "6.5.1 Understand basic database concepts" },
          { id: "6.5.2", title: "6.5.2 Explain the steps for connecting to a database" },
          { id: "6.5.3", title: "6.5.3 Steps to retrieve/insert/update/delete data" },
          { id: "6.5.4", title: "6.5.4 Write programs on DDL and DML Commands" },
        ]
      }
    ]
  },
  {
    id: "python",
    title: "Python Programming",
    description: "Learn Python basics, IoT concepts, and Raspberry Pi integration.",
    icon: "Terminal",
    chapters: [
      {
        id: "p1",
        title: "1. Python Introduction and Raspberry PI",
        topics: [
          { id: "p1.1", title: "1.1 Define IOT" },
          { id: "1.2", title: "1.2 List applications of IOT" },
          { id: "1.3", title: "1.3 List Advantages and Disadvantages of IOT" },
          { id: "1.4", title: "1.4 Identify Components of Raspberry PI-3" },
          { id: "1.5", title: "1.5 List General purpose input and Output pins (GPIO) on Raspberry PI" },
          { id: "1.6", title: "1.6 Build a PC using Raspberry PI-3" },
          { id: "1.7", title: "1.7 Install operating System into Raspberry PI" },
          { id: "1.8", title: "1.8 Familiarize to python programming language" },
          { id: "1.9", title: "1.9 List different versions of pythons" },
          { id: "1.10", title: "1.10 Compare Python programming language with Java Programming language" },
          { id: "1.11", title: "1.11 Lists features of Python programming" },
          { id: "1.12", title: "1.12 Sets the execution environment for Python" },
          { id: "1.13", title: "1.13 Execute Python Script (Command Prompt, Script and IDE) in different ways" },
        ]
      },
      {
        id: "p2",
        title: "2. Basic of Python programming",
        topics: [
          { id: "2.1", title: "2.1 Declare and initialize variables" },
          { id: "2.2", title: "2.2 Use Comments, Indentation in programs" },
          { id: "2.3", title: "2.3 Discuss Data Types Booleans, Numbers" },
          { id: "2.4", title: "2.4 Use Decision Making Statements to solve different problems" },
          { id: "2.5", title: "2.5 Use Loop Statements with example to solve problems which are iterative" },
          { id: "2.6", title: "2.6 Perform operation on Lists, Tuples, Sets, and Dictionaries" },
          { id: "2.7", title: "2.7 Identify members of Lists, Tuples, Sets, and Dictionaries using Membership Operator" },
          { id: "2.8", title: "2.8 Process strings using operators and built-in functions" },
          { id: "2.9", title: "2.9 Build functions with/without arguments" },
          { id: "2.10", title: "2.10 Solve problems by using recursive method of problem solving" },
          { id: "2.11", title: "2.11 Differentiate between recursive and iterative way of problem solving" },
        ]
      },
      {
        id: "p3",
        title: "3. Classes and Packages",
        topics: [
          { id: "3.1", title: "3.1 Define class with its members and create instances of class" },
          { id: "3.2", title: "3.2 Implement different types of Inheritance" },
          { id: "3.3", title: "3.3 Use super to call methods of a super class" },
          { id: "3.4", title: "3.4 Use Python Identity Operator" },
          { id: "3.5", title: "3.5 Create and import Modules and Packages" },
          { id: "3.6", title: "3.6 Use local and global variables" },
          { id: "3.7", title: "3.7 Sets up the virtual environment for python application" },
          { id: "3.8", title: "3.8 Install packages" },
          { id: "3.9", title: "3.9 Write programs using standard Mathematical functions (sqrt, cos, etc.)" },
          { id: "3.10", title: "3.10 Use datetime package in python application" },
        ]
      },
      {
        id: "p4",
        title: "4. Exception handling and Multithreading",
        topics: [
          { id: "4.1", title: "4.1 Difference between compile time, runtime and logical errors" },
          { id: "4.2", title: "4.2 List common compile time errors and runtime errors" },
          { id: "4.3", title: "4.3 Using try/except, finally and else block to handle exceptions" },
          { id: "4.4", title: "4.4 Usage of raise statement" },
          { id: "4.5", title: "4.5 Create User defined exception classes" },
          { id: "4.6", title: "4.6 Define Multithreading" },
          { id: "4.7", title: "4.7 List pros and cons of Multithreading" },
          { id: "4.8", title: "4.8 Create threads using Threading Module" },
          { id: "4.9", title: "4.9 Create Multiple Threads which perform different tasks" },
          { id: "4.10", title: "4.10 Design threads using start, join, isAlive, etc." },
          { id: "4.11", title: "4.11 Achieve thread Synchronization in multithreaded environment" },
        ]
      },
      {
        id: "p5",
        title: "5. Design Graphical user Interface and Regular Expressions",
        topics: [
          { id: "5.1", title: "5.1 Design a Graphical User Interface using TKinter library" },
          { id: "5.2", title: "5.2 Design GUI using different Geometry Managers" },
          { id: "5.3", title: "5.3 Use various Widgets in TKinter library" },
          { id: "5.4", title: "5.4 List attributes of widgets" },
          { id: "5.5", title: "5.5 Handle Events generated by various Widgets" },
          { id: "5.6", title: "5.6 Create patterns to use regular expressions" },
          { id: "5.7", title: "5.7 Validate data using regular expressions" },
        ]
      },
      {
        id: "p6",
        title: "6. Data Processing and Programming Raspberry Pi",
        topics: [
          { id: "6.1", title: "6.1 Open, close, read, write, append data to files using programs" },
          { id: "6.2", title: "6.2 List modes of opening a file" },
          { id: "6.3", title: "6.3 Delete files and folders" },
          { id: "6.4", title: "6.4 Connect to MySql database" },
          { id: "6.5", title: "6.5 Create table, insert, update and execute stored procedures" },
          { id: "6.6", title: "6.6 Store images using blob data type" },
          { id: "6.7", title: "6.7 Use Bread board, resistor, transistors, diode, etc." },
          { id: "6.8", title: "6.8 Work with I2C and SPI interface of Raspberry PI" },
          { id: "6.9", title: "6.9 Turn On and Off LED using python program" },
          { id: "6.10", title: "6.10 Make a buzzing sound with Raspberry Pi and python program" },
          { id: "6.11", title: "6.11 Connect to Wired or Wireless network" },
        ]
      }
    ]
  },
  {
    id: "dotnet",
    title: ".NET Programming through C#",
    description: "Build Windows and Web applications using the C# language and .NET Framework.",
    icon: "Monitor",
    chapters: [
      {
        id: "d1",
        title: "1. Basics of .NET Framework and Visual Studio",
        topics: [
          { id: "1.1", title: "1.1 Define .NET Framework" },
          { id: "1.2", title: "1.2 List the features of .NET framework" },
          { id: "1.3", title: "1.3 Draw and grasp CLR architecture" },
          { id: "1.4", title: "1.4 Discuss about .NET framework and base class Library" },
          { id: "1.5", title: "1.5 List .NET languages" },
          { id: "1.6", title: "1.6 List the features of Visual Studio for C#.NET" },
          { id: "1.7", title: "1.7 Purpose of Design View, Code window, Object browser, Solution Explorer" },
          { id: "1.8", title: "1.8 List the applications of .NET" },
        ]
      },
      {
        id: "d2",
        title: "2. Introduction to C#.NET",
        topics: [
          { id: "2.1", title: "2.1 Familiarize with C#.net" },
          { id: "2.2", title: "2.2 List features of C#.net" },
          { id: "2.3", title: "2.3 Differentiate between C#.Net and C/C++" },
          { id: "2.4", title: "2.4 Differentiate between C#.Net and Java" },
          { id: "2.5", title: "2.5 Explain Different primitive data types" },
          { id: "2.6", title: "2.6 Build data types using class, struct, enum, and interface" },
          { id: "2.7", title: "2.7 Design applications using instance/local variables and methods" },
          { id: "2.8", title: "2.8 Example programs with constructors in classes and structures" },
          { id: "2.9", title: "2.9 Control access to members with access specifiers" },
          { id: "2.10", title: "2.10 Discuss about inheriting classes" },
          { id: "2.11", title: "2.11 Process data with different types of arrays" },
          { id: "2.12", title: "2.12 Develop programs using Method Overloading and Overriding" },
          { id: "2.13", title: "2.13 Differentiate looping structure with recursive function call" },
        ]
      },
      {
        id: "d3",
        title: "3. Exception Handling and Multithreading",
        topics: [
          { id: "3.1", title: "3.1 Define Exception" },
          { id: "3.2", title: "3.2 List Predefined Exception Classes" },
          { id: "3.3", title: "3.3 Handle Exceptions" },
          { id: "3.4", title: "3.4 Create user defined exceptions" },
          { id: "3.5", title: "3.5 Define Multithreading, Threads" },
          { id: "3.6", title: "3.6 Comprehend thread class properties and methods" },
          { id: "3.7", title: "3.7 Create and abort threads" },
          { id: "3.8", title: "3.8 List the states of thread life cycle" },
          { id: "3.9", title: "3.9 Create Multiple Threads" },
          { id: "3.10", title: "3.10 List Thread priorities" },
        ]
      },
      {
        id: "d4",
        title: "4. Advanced concepts of C#",
        topics: [
          { id: "4.1", title: "4.1 Design classes with Indexers and Properties" },
          { id: "4.2", title: "4.2 Define Anonymous Methods in classes" },
          { id: "4.3", title: "4.3 Pass Parameters and Returns values from anonymous methods" },
          { id: "4.4", title: "4.4 List types of Lambda expressions with examples" },
          { id: "4.5", title: "4.5 Delegates functionality to other functions" },
          { id: "4.6", title: "4.6 Use operators like is, as and typeof" },
          { id: "4.7", title: "4.7 List the needs of Generic Programming" },
          { id: "4.8", title: "4.8 Define Generic class with two parameters" },
        ]
      },
      {
        id: "d5",
        title: "5. Windows and Web Applications development",
        topics: [
          { id: "5.1", title: "5.1 Designing aspects of C#.NET windows application form" },
          { id: "5.2", title: "5.2 List the steps for creating a windows application" },
          { id: "5.3", title: "5.3 List various elements of user interface" },
          { id: "5.4", title: "5.4 Properties of controls (textbox, label, button, datagrid, etc.)" },
          { id: "5.5", title: "5.5 Enable, disable, hide, and show controls in windows app" },
          { id: "5.6", title: "5.6 Handle events generated by various controls" },
          { id: "5.7", title: "5.7 List the steps for creation of Menus at design time" },
          { id: "5.8", title: "5.8 Develop a project to control menus at run time" },
          { id: "5.9", title: "5.9 Create short cut keys for pull down menus" },
          { id: "5.10", title: "5.10 Steps to deploy and distribute a windows application" },
          { id: "5.11", title: "5.11 Steps for creating a web application" },
          { id: "5.12", title: "5.12 Usage of web controls (textbox, label, button, listbox, etc.)" },
          { id: "5.13", title: "5.13 List and describe various Data validation controls" },
          { id: "5.14", title: "5.14 Importance of data transfer between pages" },
          { id: "5.15", title: "5.15 Use query string, cookie and post method for data transfer" },
        ]
      },
      {
        id: "d6",
        title: "6. Database access",
        topics: [
          { id: "6.1", title: "6.1 Familiarize with ADO.NET" },
          { id: "6.2", title: "6.2 List the features and advantages of ADO.NET" },
          { id: "6.3", title: "6.3 Establish connection using Connection, Dataset, Data adapter, etc." },
          { id: "6.4", title: "6.4 Connect database to C# application through server explorer" },
          { id: "6.5", title: "6.5 Differentiate between typed and untyped dataset objects" },
          { id: "6.6", title: "6.6 Access data with data adapters and typed/untyped data sets" },
          { id: "6.7", title: "6.7 Explain databinding to DataGrid control, textbox and listbox" },
          { id: "6.8", title: "6.8 Explain how to navigate through a data source" },
          { id: "6.9", title: "6.9 Familiarize to LINQ" },
          { id: "6.10", title: "6.10 Write Syntax of LINQ" },
          { id: "6.11", title: "6.11 List Types of LINQ Objects" },
          { id: "6.12", title: "6.12 List the advantages of LINQ" },
          { id: "6.13", title: "6.13 List various LINQ operators" },
        ]
      }
    ]
  },
  {
    id: "ai",
    title: "Artificial Intelligence",
    description: "Explore AI concepts, search algorithms, knowledge representation, and machine learning.",
    icon: "Brain",
    chapters: [
      {
        id: "ai1",
        title: "1. Introduction to Artificial Intelligence",
        topics: [
          { id: "1.1", title: "1.1 Define Artificial Intelligence" },
          { id: "1.2", title: "1.2 State the need for Artificial Intelligence" },
          { id: "1.3", title: "1.3 Explain AI techniques" },
          { id: "1.4", title: "1.4 Explain the approaches to Artificial Intelligence" },
          { id: "1.5", title: "1.5 Brief history of Artificial Intelligence" },
          { id: "1.6", title: "1.6 List the applications of Artificial Intelligence" },
          { id: "1.7", title: "1.7 Explain search in state spaces and mention its advantages" },
          { id: "1.8", title: "1.8 Memory vs Computation – brief note" },
          { id: "1.9", title: "1.9 Explain state space graph" },
          { id: "1.10", title: "1.10 Explain searching explicit state spaces" },
          { id: "1.11", title: "1.11 Explain feature-based state spaces" },
          { id: "1.12", title: "1.12 Uninformed search strategies: BFS and DFS" },
          { id: "1.13", title: "1.13 Differentiate BFS and DFS" },
          { id: "1.14", title: "1.14 Heuristic functions – definition and examples" },
        ]
      },
      {
        id: "ai2",
        title: "2. Basic Knowledge Representation and Reasoning",
        topics: [
          { id: "2.1", title: "2.1 Knowledge Representation and Reasoning – overview" },
          { id: "2.2", title: "2.2 Propositional Calculus / Logic – detailed explanation" },
          { id: "2.3", title: "2.3 Semantics of Propositional Logic – list" },
          { id: "2.4", title: "2.4 Define Resolution in Propositional Logic" },
          { id: "2.5", title: "2.5 Explain Semantics in Propositional Logic" },
          { id: "2.6", title: "2.6 PSAT Problem – brief note" },
          { id: "2.7", title: "2.7 Predicate Calculus – language and syntax" },
          { id: "2.8", title: "2.8 Semantics of Predicate Logic – list" },
          { id: "2.9", title: "2.9 Explain semantics in Predicate Logic" },
          { id: "2.10", title: "2.10 State Horn Clauses" },
          { id: "2.11", title: "2.11 Define First-Order Logic (FOL)" },
          { id: "2.12", title: "2.12 Explain Forward Chaining Algorithm" },
          { id: "2.13", title: "2.13 Explain Backward Chaining Algorithm" },
        ]
      },
      {
        id: "ai3",
        title: "3. Reasoning Under Uncertainty",
        topics: [
          { id: "3.1", title: "3.1 Define Conditional Probability" },
          { id: "3.2", title: "3.2 Explain Probabilistic Inference with example" },
          { id: "3.3", title: "3.3 Explain Bayes Networks" },
          { id: "3.4", title: "3.4 List types of inference in Bayes Networks" },
          { id: "3.5", title: "3.5 Explain types of inference in Bayes Networks" },
          { id: "3.6", title: "3.6 State Uncertain Evidence" },
          { id: "3.7", title: "3.7 Define D-Separation" },
          { id: "3.8", title: "3.8 Probabilistic Inference in Polytrees – explanation" },
          { id: "3.9", title: "3.9 Explain reasoning on states and actions" },
          { id: "3.10", title: "3.10 List difficulties in reasoning with uncertain information" },
          { id: "3.11", title: "3.11 Explain difficulties in reasoning with uncertain information" },
          { id: "3.12", title: "3.12 Generate plans – brief explanation" },
        ]
      },
      {
        id: "ai4",
        title: "4. Learning from Observations",
        topics: [
          { id: "4.1", title: "4.1 Define Learning" },
          { id: "4.2", title: "4.2 Forms of Learning – explanation" },
          { id: "4.3", title: "4.3 Inductive Learning with example" },
          { id: "4.4", title: "4.4 Define Decision Tree" },
          { id: "4.5", title: "4.5 List advantages of Decision Trees" },
          { id: "4.6", title: "4.6 Use of Decision Trees to describe domain – with example" },
          { id: "4.7", title: "4.7 Decision Tree Learning Algorithm – with example" },
          { id: "4.8", title: "4.8 Procedure for selecting attribute tests" },
          { id: "4.9", title: "4.9 Define Overfitting Problem" },
          { id: "4.10", title: "4.10 Techniques to handle Overfitting" },
          { id: "4.11", title: "4.11 Issues in extending applicability of Decision Trees" },
          { id: "4.12", title: "4.12 Define False Negative and False Positive" },
          { id: "4.13", title: "4.13 Current-Best-Hypothesis test – procedure" },
          { id: "4.14", title: "4.14 Version Space Learning – explanation" },
        ]
      },
      {
        id: "ai5",
        title: "5. Natural Language Processing",
        topics: [
          { id: "5.1", title: "5.1 Define Natural Language" },
          { id: "5.2", title: "5.2 Advantages of Natural Language Processing" },
          { id: "5.3", title: "5.3 Steps involved in a communication agent" },
          { id: "5.4", title: "5.4 Morphological Analysis – explanation" },
          { id: "5.5", title: "5.5 Define Parsing" },
          { id: "5.6", title: "5.6 Parse a sentence – with example" },
          { id: "5.7", title: "5.7 Explain Transition Networks" },
          { id: "5.8", title: "5.8 Augmented Transition Networks – definition" },
          { id: "5.9", title: "5.9 Chart Parsing – statement" },
          { id: "5.10", title: "5.10 Semantic Analysis in NLP – explanation" },
          { id: "5.11", title: "5.11 Pragmatic Analysis in understanding natural language" },
          { id: "5.12", title: "5.12 Ambiguity and Disambiguation – statement" },
          { id: "5.13", title: "5.13 Forms of Ambiguity – detailed explanation" },
          { id: "5.14", title: "5.14 Discourse Understanding – statement" },
        ]
      },
      {
        id: "ai6",
        title: "6. Applications of Artificial Intelligence",
        topics: [
          { id: "6.1", title: "6.1 Speech Recognition with different models" },
          { id: "6.2", title: "6.2 Major design issues in speech recognition systems" },
          { id: "6.3", title: "6.3 AI role in computer applications" },
          { id: "6.4", title: "6.4 AI role in robotics" },
          { id: "6.5", title: "6.5 AI role in flying with drones" },
          { id: "6.6", title: "6.6 Future of AI-driven cars" },
          { id: "6.7", title: "6.7 AI role in observing the universe" },
          { id: "6.8", title: "6.8 AI role in developing neural networks" },
          { id: "6.9", title: "6.9 AI in the medical field" },
          { id: "6.10", title: "6.10 AI in military applications" },
        ]
      }
    ]
  },
  {
    id: "management",
    title: "Industrial Management & Entrepreneurship",
    description: "Learn management principles, production planning, quality control, and entrepreneurship.",
    icon: "Briefcase",
    chapters: [
      {
        id: "ime1",
        title: "1. Principles & Functions of Management, Org Structure & Behavior",
        topics: [
          { id: "1.1", title: "1.1 Define industry, commerce (trade), and business" },
          { id: "1.2", title: "1.2 Need for management" },
          { id: "1.3", title: "1.3 Evolution of management" },
          { id: "1.4", title: "1.4 Principles of scientific management" },
          { id: "1.5", title: "1.5 Functions of management" },
          { id: "1.6", title: "1.6 Difference between management and administration" },
          { id: "1.7", title: "1.7 Types of ownership" },
          { id: "1.8", title: "1.8 Differences between types of ownership" },
          { id: "1.9", title: "1.9 Salient features of joint stock companies" },
          { id: "1.10", title: "1.10 Philosophy and need for organization structure in an industry" },
          { id: "1.11", title: "1.11 Line, Staff, and Functional organizations" },
          { id: "1.12", title: "1.12 Advantages and limitations of Line, Staff & Functional orgs" },
          { id: "1.13", title: "1.13 Departments in a large-scale industry" },
          { id: "1.14", title: "1.14 Factors of effective organization" },
          { id: "1.15", title: "1.15 Organizational behavior – understanding" },
          { id: "1.16", title: "1.16 Job analysis – explanation" },
          { id: "1.17", title: "1.17 Motivation theories – statement" },
          { id: "1.18", title: "1.18 Maslow’s Hierarchy of Needs" },
          { id: "1.19", title: "1.19 Leadership models – list" },
          { id: "1.20", title: "1.20 Trait theory and behavior theory of leadership" },
        ]
      },
      {
        id: "ime2",
        title: "2. Functions of Production Management",
        topics: [
          { id: "2.1", title: "2.1 Difference between production, planning, and control" },
          { id: "2.2", title: "2.2 Relationship of production department with other departments" },
          { id: "2.3", title: "2.3 Need for planning and its advantages" },
          { id: "2.4", title: "2.4 Stages of Production Planning and Control (PPC)" },
          { id: "2.5", title: "2.5 Routing methods" },
          { id: "2.6", title: "2.6 Scheduling methods" },
          { id: "2.7", title: "2.7 Dispatching – explanation" },
          { id: "2.8", title: "2.8 PERT/CPM network diagrams – drawing" },
          { id: "2.9", title: "2.9 Identification of the critical path" },
          { id: "2.10", title: "2.10 Problems on PERT & CPM" },
        ]
      },
      {
        id: "ime3",
        title: "3. Materials Management",
        topics: [
          { id: "3.1", title: "3.1 Importance of materials management" },
          { id: "3.2", title: "3.2 Objectives and functions of materials management" },
          { id: "3.3", title: "3.3 Derivation of EOQ (Economic Order Quantity)" },
          { id: "3.4", title: "3.4 ABC analysis – explanation" },
          { id: "3.5", title: "3.5 Define Safety Stock and Buffer Stock" },
          { id: "3.6", title: "3.6 Define Reorder Level" },
          { id: "3.7", title: "3.7 Stores department functions & duties of storekeeper" },
          { id: "3.8", title: "3.8 Stores layout – explanation" },
          { id: "3.9", title: "3.9 Stores records – explanation" },
          { id: "3.10", title: "3.10 Cardex method – description" },
          { id: "3.11", title: "3.11 Objectives and functions of purchasing department" },
          { id: "3.12", title: "3.12 Purchasing procedures" },
          { id: "3.13", title: "3.13 Purchase records – list" },
          { id: "3.14", title: "3.14 Stores equipment – description" },
        ]
      },
      {
        id: "ime4",
        title: "4. Marketing, Sales & Feasibility Study",
        topics: [
          { id: "4.1", title: "4.1 Marketing functions – explanation" },
          { id: "4.2", title: "4.2 Sales function – explanation" },
          { id: "4.3", title: "4.3 Marketing conditions – list" },
          { id: "4.4", title: "4.4 Difference between sellers’ market and buyers’ market" },
          { id: "4.5", title: "4.5 Difference between monopoly, oligopoly, and perfect competition" },
          { id: "4.6", title: "4.6 Steps in conducting market and demand surveys" },
          { id: "4.7", title: "4.7 Advantages and disadvantages of market & demand surveys" },
          { id: "4.8", title: "4.8 Difference between product analysis and production analysis" },
          { id: "4.9", title: "4.9 Identification of input materials (Bill of Materials)" },
          { id: "4.10", title: "4.10 Concept of cost – explanation" },
          { id: "4.11", title: "4.11 Break-even analysis – explanation" },
          { id: "4.12", title: "4.12 Evaluation of economic and technical factors" },
          { id: "4.13", title: "4.13 Preparation of feasibility study" },
          { id: "4.14", title: "4.14 List of products currently in demand in market/industry" },
        ]
      },
      {
        id: "ime5",
        title: "5. ISO 9000 & Total Quality Management (TQM)",
        topics: [
          { id: "5.1", title: "5.1 Concept of quality – understanding" },
          { id: "5.2", title: "5.2 Quality systems and elements of quality systems" },
          { id: "5.3", title: "5.3 Principles of quality assurance" },
          { id: "5.4", title: "5.4 Evolution of ISO standards" },
          { id: "5.5", title: "5.5 ISO standards and ISO 9000 series of quality systems – discussion" },
          { id: "5.6", title: "5.6 Constituents of ISO 9000 series of standards" },
          { id: "5.7", title: "5.7 Benefits and drawbacks of ISO 9000 series" },
          { id: "5.8", title: "5.8 Beneficiaries of ISO 9000 – list" },
          { id: "5.9", title: "5.9 5-S principles and Zero Defect – understanding" },
          { id: "5.10", title: "5.10 TQM – concept and elements" },
        ]
      },
      {
        id: "ime6",
        title: "6. Industrial Legislation, Safety & Entrepreneurship Development",
        topics: [
          { id: "6.1", title: "6.1 Employer–Employee relations – description" },
          { id: "6.2", title: "6.2 Trade Unions: objectives, functions, advantages & disadvantages" },
          { id: "6.3", title: "6.3 Causes and settlement of industrial disputes" },
          { id: "6.4", title: "6.4 Welfare activities – list" },
          { id: "6.5", title: "6.5 Rights & responsibilities of employees and employers" },
          { id: "6.6", title: "6.6 Salient features of Indian Factories Act" },
          { id: "6.7", title: "6.7 Importance of safety at workplace" },
          { id: "6.8", title: "6.8 Important safety provisions – list" },
          { id: "6.9", title: "6.9 Hazard and accident – explanation" },
          { id: "6.10", title: "6.10 Causes of accidents – explanation" },
          { id: "6.11", title: "6.11 Define entrepreneur" },
          { id: "6.12", title: "6.12 Difference between entrepreneurship and management" },
          { id: "6.13", title: "6.13 Expectations, roles & qualities of an entrepreneur" },
          { id: "6.14", title: "6.14 Role of entrepreneurs in promoting small-scale industries" },
          { id: "6.15", title: "6.15 Self-employment schemes – description" },
          { id: "6.16", title: "6.16 Method of product selection" },
          { id: "6.17", title: "6.17 Method of site selection" },
          { id: "6.18", title: "6.18 Financial assistance programs – list" },
          { id: "6.19", title: "6.19 Organizations supporting entrepreneurs – list" },
          { id: "6.20", title: "6.20 Importance of Start-ups" },
          { id: "6.21", title: "6.21 Different Start-up schemes" },
          { id: "6.22", title: "6.22 Features & eligibility for Start-up registration" },
          { id: "6.23", title: "6.23 Benefits of Start-ups" },
        ]
      }
    ]
  }
];
